apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicontagemrabbitmqdotnet6 
spec:
  selector:
    matchLabels:
      app: apicontagemrabbitmqdotnet6
  replicas: 10
  template:
    metadata:
      labels:
        app: apicontagemrabbitmqdotnet6 
    spec:
      containers:
        - name: apicontagemrabbitmqdotnet6 
          image: renatogroffe/apicontagem-rabbitmq-dotnet6:1
          ports:
          - containerPort: 80
          env:
          - name: RabbitMQ__Queue
            value: queue-testes
          - name: RabbitMQ__ConnectionString
            valueFrom:
              secretKeyRef:
                name: workercontagemsecret
                key: ConnectionRabbitMQ
          - name: ConnectionStrings__BaseContagem
            valueFrom:
              secretKeyRef:
                name: workercontagemsecret
                key: ConnectionSqlServer
---
apiVersion: v1
kind: Service
metadata:
    name: apicontagemrabbitmqdotnet6
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: apicontagemrabbitmqdotnet6